version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

# No .html on files
sphinx:
  builder: dirhtml
  configuration: docs/conf.py

# Newish Python
python:
  version: 3.7
  install:
    - requirements: requirements.txt

# No PDF
formats: []
