version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"


python:
  install:
    - requirements: requirements.txt

# No .html on files
sphinx:
  builder: dirhtml
  configuration: docs/conf.py

# No PDF
formats: []
