name: Australia & India

shortcode: australia # australia australia?
year: 2021
city: Melbourne
local_area: Australia
area: Australia
area_adj: Australian
tz: AEDT
email: australia@writethedocs.org
color: gold
rgb: 253,185,19
hex: fdb913

photos:
  default: _static/conf/images/headers/WTDHeader.png

buttons:
  top:
#    - text: Welcome to our conference
#      link: /news/welcome
#    - text: Date and ticket information
#      link: /news/announcing-virtual-conf-dates-tickets
    # - text: Read our conference guide
    #   link: /welcome-wagon
    # - text: See the Schedule!
    #   link: /schedule
    - text: Buy a Ticket!
      link: /tickets
#    - text: Sponsor us
#      link: /sponsors/prospectus
    - text: Submit a Talk
      link: /cfp
    #- text: See the talks!
    #   link: /speakers
    # - text: See the Schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ
  bottom:
     - text: Welcome to our conference
       link: /news/welcome
    # - text: See the Schedule!
    #   link: /schedule
#     - text: Date and ticket information
#       link: /news/announcing-virtual-conf-dates-tickets
     - text: Sponsor the conference
       link: /sponsors/prospectus
    # - text: See the talks!
    #   link: /speakers
     - text: Buy a Ticket!
       link: /tickets
    # - text: Prepare with the Welcome Wagon
    #   link: /welcome-wagon
    # - text: See the schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ

tickets:
  corporate:
    price: $175
  independent:
    price: $100
  student:
    price: $25

sponsorship:
  first_draft:
    price: AUD $500
  second_draft:
    price: AUD $1000
  publisher:
    price: AUD $2000
  patron:
    price: AUD $4000
  keystone:
    price: AUD $7500

date: # how do we handle these? human readable would be nice.
  main: "**December 2-3, 2021, online**"
  short: Dec 2-3, 2021
  tickets_live: "May 2021"
  month: December
  day_one:
    event: Conference Day 1
    date: December 2
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Thursday
    talk_time: 12:00-19:00
    unconference_time: 15:00-17:00
    icon: conference
  day_two:
    event: Conference Day 2
    date: December 3
    summary: And the conference goes on! We are already starting to miss you. |:heart:|
    dotw: Friday
    talk_time: 12:00-18:00
    unconference_time: 15:00-17:00
    icon: conference
  total_talk_days: 2

about:
  attendees: 150
  summary:
    "The main presentation track takes place during **December 2-3 (Thursday and Friday) from 12:00pm to 7:00pm AEDT**.
    During the main event we also run an :doc:`/conf/australia/2021/unconference`."
  venue:
    "Online, https://hopin.to/. Your login will be emailed to you before the event"
  mainroom: "Video area"
  unconfroom: "Chat area"
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"

cfp:
  url: https://pretalx.com/wtd-australia-and-india-2021/cfp
  ends: "August 15, 2021"           # 2 weeks to review and get confirmnations
  notification: "September 10, 2021"   # leaves 6 weeks to write and record
  video_by: "November 1, 2021"   # 4 weeks before the conf

grants:
  url: https://docs.google.com/forms/d/e/1FAIpQLSe7IUKVckN5m-C_x9JguqwT3zt_PctyCl62yCkCf6D73be99A/viewform
  ends: "October 15, 2021"
  notification: "October 31, 2021"


sponsors:
  keystone:
  patron:
  publisher:
  second:
  first:


# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: False
flagcfp: True
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flaghasunconf: False
flaghasshirts: False
flagvideos: False
flaglivestreaming: False
flagpostconf: False

# Truthy things that don't change
flaghashike: False
flaghasboat: False
flaghaswritingday: False
flaghasjobfair: True
flaghasbadgeflair: False
