name: Australia & India

shortcode: australia # australia australia?
year: 2021
city: Melbourne
local_area: Australia
area: Australia
area_adj: Australian
tz: AEDT
email: australia@writethedocs.org
color: gold
rgb: 253,185,19
hex: fdb913

photos:
  default: _static/conf/images/headers/WTDHeader.png

buttons:
  top:
    - text: Welcome to our conference
      link: /news/welcome
#    - text: Date and ticket information
#      link: /news/announcing-virtual-conf-dates-tickets
    # - text: Read our conference guide
    #   link: /welcome-wagon
    # - text: See the Schedule!
    #   link: /schedule
#    - text: Buy a Ticket!
#      link: /tickets
    - text: Sponsor us
      link: /sponsors/prospectus
    #- text: Submit a Talk
    #  link: /cfp
    #- text: See the talks!
    #   link: /speakers
    # - text: See the Schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ
  bottom:
     - text: Welcome to our conference
       link: /news/welcome
    # - text: See the Schedule!
    #   link: /schedule
#     - text: Date and ticket information
#       link: /news/announcing-virtual-conf-dates-tickets
     - text: Sponsor the conference
       link: /sponsors/prospectus
    # - text: See the talks!
    #   link: /speakers
#     - text: Buy a Ticket!
#       link: /tickets
    # - text: Prepare with the Welcome Wagon
    #   link: /welcome-wagon
    # - text: See the schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ

tickets:
  corporate:
    price: $150
  independent:
    price: $100
  student:
    price: $50

sponsorship:
  first_draft:
    price: $500
  second_draft:
    price: $1000
  publisher:
    price: $2000
  patron:
    price: $4000
  keystone:
    price: $7500

date: # how do we handle these? human readable would be nice.
  main: "**December 2-3, 2021, online**"
  short: Dec 2-3, 2021
  tickets_live: "May 2021"
  month: December
  day_one:
    event: Conference Day 1
    date: December 2
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Thursday
    talk_time: 10:00-18:00
    unconference_time: 9:45-17:00
    icon: conference
  day_two:
    event: Conference Day 2
    date: December 3
    summary: And the conference goes on! We are already starting to miss you. |:heart:|
    dotw: Friday
    talk_time: 10:00-18:00
    job_fair_time: 9:45-12:00
    unconference_time: 14:15-17:00
    icon: conference
  total_talk_days: 2

about:
  attendees: 150
  summary:
    "The main presentation track takes place during **December 2-3 (Thursday and Friday) from 11:00am to 7:00pm AEDT**.
    During the main event we also run an :doc:`/conf/australia/2020/unconference`."
  venue:
    "Online, https://hopin.to/. Your login will be emailed to you before the event"
  mainroom: "Video area"
  unconfroom: "Chat area"
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"

sponsors:
  keystone:
  patron:
  publisher:
  second:
  first:


# Things that change over time, listed in order of change
flaglanding: True
flaghassponsors: False
flagcfp: False
flagticketsonsale: False
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flaghasunconf: False
flaghasshirts: False
flagvideos: False
flaglivestreaming: False
flagpostconf: False

# Truthy things that don't change
flaghashike: False
flaghasboat: False
flaghaswritingday: True
flaghasjobfair: True
flaghasbadgeflair: False
