name: Portland

shortcode: portland # prague australia?
year: 2024
city: Portland
local_area: Oregon
area: North America # European Australian
area_adj: North American
tz: Pacific Time  # PT until March, PST after... :/
email: portland@writethedocs.org
color: blue
rgb: 74, 193, 224
hex: 4AC1E0
time_format: 12h

photos:
  default: _static/conf/images/headers/group.png

buttons:
  top:
    # - text: Date and ticket information
    #   link: /news/welcome/
    - text: Submit a Talk
      link: /cfp
    - text: Sponsor us
      link: /sponsors/prospectus
    #   - text: Read our conference guide
    #     link: /welcome-wagon
    #   - text: See the Schedule!
    #     link: /schedule
    # - text: Buy a Ticket!
    #   link: /tickets
    #  - text: See the talks!
    #    link: /speakers
    #  - text: Schedule
    #    link: /schedule
    #  - text: Attendee Guide
    #    link: /welcome-wagon
    #   - text: Watch the Live Stream
    #     link: /livestream
    # - text: Watch the videos
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpneQPsDWa4OmEpgW4pNiaZ2
    # - text: Conference recap
    #   link: /news/thanks-recap
  bottom:
    # - text: Welcome to our conference
    #   link: /news/welcome
    - text: Sponsor the conference
      link: /sponsors/prospectus
    - text: Submit a Talk
      link: /cfp
  #  - text: See the Schedule
  #    link: /schedule
  #   - text: Date and ticket information
  #     link: /news/announcing-virtual-conf-dates-tickets
  #   - text: See the talks!
  #     link: /speakers
    # - text: Buy a Ticket!
    #   link: /tickets
  #  - text: Read our guide
  #    link: /welcome-wagon
  #  - text: See the schedule!
  #    link: /schedule
  #   - text: Watch the Live Stream
  #     link: /livestream
  # - text: Conference recap
  #   link: /news/thanks-recap
  # - text: Browse the photos
  #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72177720308088427
  #   - text: Watch the videos!
  #     link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ

tickets:
  concierge:
    price: $750
  corporate:
    price: $650
  independent:
    price: $350
  student:
    price: $100

sponsorship:
  second_draft:
    price: $2,500
  publisher:
    price: $5,000
  patron:
    price: $8,500
  keystone:
    price: $14,000

grants:
  url: 'https://docs.google.com/forms/d/e/1FAIpQLSfA1G4jnsUTWQeQnUtUJ3QUFcwokEAH8MrMamFaNs64LN-5Xg/viewform'
  ends: 'February 1, 2024'
  notification: 'February 14, 2024'

shirts:
  url: https://teespring.com/wtd-pdx-2024
  ends: "May 31, 2024"

date: # how do we handle these? human readable would be nice.
  main: "**April 14-16, 2024**"
  short: April 14-16, 2024
  tickets_live: "December 2023"
  month: April

  # Conference is special for the index to show the combined conference days
  conference:
    event: Speaker talks
    date: April 15-16
    summary: The main days of the conference. Listen to a diverse panel of speakers share their insights and experience. Currently accepting <a href="https://www.writethedocs.org/conf/portland/2024/cfp/">Call for Proposals</a>.
    icon: conference

  # These are listed in the schedule
  day_one:
    event: Hike
    date: April 13
    # summary: We encourage you to go on a hike in your own beautiful home town.
    summary: If you're in town early, join us for the  <a href="/conf/portland/2024/outing/">hike</a>. Portland has excellent access to the woods right in the city.
    icon: hike
    dotw: Saturday
  day_two:
    event: Writing Day & Reception
    date: April 14
    summary: Kick off the conference with <a href="/conf/portland/2024/writing-day/">Writing Day</a> and work with fellow documentarians on a project. Followed by the opening reception.
    icon: writing
    dotw: Sunday
    writing_day_time: 9am-5pm
    reception_time: 5-7pm
  day_three:
    event: Conference Day 1
    date: April 15
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Monday
    talk_time: 9am-5pm
    unconference_time: 9:45am-5pm
    social_time: 7-9pm
    icon: conference
  day_four:
    event: Conference Day 2
    date: April 16
    summary: And the conference goes on! More talks and unconference today, along with our Sponsor Expo!
    dotw: Tuesday
    talk_time: 9am-4pm
    job_fair_time: 9-12pm
    unconference_time: 1:35pm-4pm
    icon: conversation
  total_talk_days: 2

about:
  attendees: 400
  summary:
    "The main presentation track takes place from **April 15-16 (Monday and Tuesday) from 9am to 5pm**.
    During the main event we also run an :doc:`/conf/portland/2024/unconference`."

  social_venue: TBD
  venue: Revolution Hall
  photos: TBD
  mainroom: Main stage
  unconfroom: Library & Astoria room (Bottom floor)
  projector_ratio: "16:9"
  job_fair_room: Sponsor area

cfp:
  url: https://pretalx.com/wtd-portland-2024/cfp  # Open November 6 (Mon) -> 9 weeks to submit
  ends: "January 15, 2024"                        # (Mon) 1 week, to review. It'll take a little longer to announce
  notification: "January 30, 2024"                # (Mon) 8 weeks to write and prepare
  slides_by: "April 7, 2024"                      # (Mon) 1 week before
  preview: "TODO"                                 # Preview URL TODO

unconf:
  url: http://bit.ly/wtd-pdx-2024-ro
  date: "All day Monday and Tuesday"

# lightning_talks:
#    signup_url: https://forms.gle/HSf9qvaRC8PVbEhu5

hike:
  date: Saturday, April 13, 1 PM

sponsors:
  keystone:
  patron:
    # - name: google
    #   link: https://www.google.com
    #   brand: Google
  publisher:
    # - name: mongodb-new
    #   link: https://www.mongodb.com/
    #   brand: MongoDB
    # - name: redocly
    #   link: https://redoc.ly/
    #   brand: Redocly
    # - name: jetbrains
    #   link: https://www.jetbrains.com/
    #   brand: JetBrains
    # - name: bloomberg-engineering
    #   link: https://www.bloomberg.com/company/careers/working-here/engineering/
    #   brand: Bloomberg Engineering
    # - name: paligo
    #   link: https://paligo.net/
    #   brand: Paligo
    #   width: 200px
    # - name: stackblitz-svg
    #   link: https://stackblitz.com/
    #   brand: StackBlitz
    # - name: cncf
    #   link: https://www.cncf.io/
    #   brand: Cloud Native Computing Foundation
    # - name: twilio
    #   link: https://www.twilio.com/
    #   brand: Twilio
    # - name: slack
    #   link: https://slack.com/
    #   brand: Slack
  second:
    - name: knowledgeowl
      link: https://www.knowledgeowl.com
      brand: KnowledgeOwl
      width: 250px
    # - name: raspberrypi
    #   link: https://www.raspberrypi.com/
    #   brand: Raspberry Pi
    # - name: readthedocs
    #   link: https://about.readthedocs.com/
    #   brand: Read the Docs
    #   width: 250px
    # - name: netlify-new
    #   link: https://www.netlify.com/
    #   brand: Netlify
    # - name: livelike
    #   link: https://livelike.com/
    #   brand: LiveLike
    # - name: openwebdocs-logo
    #   link: https://opencollective.com/open-web-docs
    #   brand: Open Web Docs
    #   width: 150px
    # - name: juniper
    #   link: https://www.juniper.net/
    #   brand: Juniper
    # - name: starburst
    #   link: https://www.starburst.io/
    #   brand: Starburst
  first:
  in_kind:
    # - name: buildkite
    #   link: https://buildkite.com/
    #   brand: Buildkite
    # - name: rtd
    #   link: https://readthedocs.com/
    #   brand: Read the Docs

# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: True
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flagscheduleincomplete: True
flaghasunconf: True
flaghasshirts: True
flaglivestreaming: False
flagvideos: False
flagpostconf: False

# Truthy things that don't change
flaghashike: True
flaghasfood: True
flaghasboat: False
flaghaswritingday: True
flaghasjobfair: True
flaghasbadgeflair: True
flaghaslightningtalks: True
