name: Vale

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


jobs:
  vale:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linter
            files: docs/
            vale_flags: "--config=vale/vale.ini"
          - name: Guide Linter
            files: docs/guide/
            vale_flags: "--config=vale/guide.ini"
          - name: Conf news Linter
            files: docs
            vale_flags: "--config=vale/news.ini --glob=docs/conf/**/news/*"
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install docutils for rst2html
        run: sudo apt-get install -y docutils

      - name: ${{ matrix.name }}
        uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{ matrix.files }}
          vale_flags: ${{ matrix.vale_flags }}
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: file
          version: 3.4.2
