name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  BUILD_VIDEOS: true


jobs:
  sphinx-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: 3.9

    - name: Cache python env
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: v2-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

    - name: Build
      shell: cmd
      working-directory: ./docs
      run: make.bat html